FROM tensorflow/tensorflow:2.17.0

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# NLTK data
RUN python -c "import nltk; nltk.download('punkt'); nltk.download('wordnet')"

COPY . .

EXPOSE 5000

CMD ["gunicorn", "chatbot:app", "--workers", "1", "--bind", "0.0.0.0:5000"]